spring:
  profiles:
    active:
      - local
  security:
    user:
      name: chruser
      password: chrpassword
      roles:
      - USER
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:chr_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: pandemichealthcareregister@gmail.com
    password: cueebzxtxangnqau
    properties:
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.auth: true
      mail.transport.protocol:  smtp
      mail.smtp.starttls.enable:  true
      mail.smtp.starttls.required:  true
      mail.smtp.ssl.enable: true
      mail.debug: true

chr:
  notification:
    email:
      from: messages-noreply@chr.com
  here:
    bearer: kvBEhyPjIjgSIBN3s1NmlgUEqVWTG7nfeXIktfiZbyc
    baseuri:  https://geocode.search.hereapi.com/v1/
  purge:
    subscriptions:
      schedule-cron:  0 23 * * * *
      expiryTimeByWeek:  1



logging:
  file:
    path: logs

server:
  tomcat:
    basedir: logs/tomcat/

  